### ISSUE TITLE
Attaching the comments to the AST nodes

### ISSUE THREAD

**Issue by yallie** [sprache/Sprache#101]
Hello, 

when developing a transpiler I needed to keep track of the source code comments, so any given class could (almost) losslessly round-trip from Apex language to C# and back again. 

Like Roslyn compilers, all comments before any given segment are leading comments, and a comment on the same line where the segment ends is a trailing comment as shown on this diagram:

![trailingcomments](https://user-images.githubusercontent.com/672878/34182086-ed837d7c-e525-11e7-84f9-c6f3c845c5c7.png)

Looks like Sprache doesn't support this out of the box, so I've come up with a couple of extension methods to support this handling of comments. The return type is

```csharp
public interface ICommented<T>
{
	IEnumerable<string> LeadingComments { get; }
	T Value { get; }
	IEnumerable<string> TrailingComments { get; }
}
```
and the usage is as follows (pseudocode):
```csharp
private Parser<BlockSyntax> Block =>
	from openBrace in Parse.Char('{').Commented() // here
	from statements in Statement.XMany()
	from closeBrace in Parse.Char('}').Commented() // and here
	select new BlockSyntax
	{
		LeadingComments = openBrace.LeadingComments,
		Statements = statements.ToList(),
		FooterComments = closeBrace.LeadingComments,
		TrailingComments = closeBrace.TrailingComments,
	};
```
This sample yields a `BlockSyntax` node that has leading comments of the opening brace and trailing comments immediately following the closing brace (on the same line as the closing brace). The `Commented` parser doesn't try to eat up all comments before and after the given node, it always stops on the same line as the decorated parser.

Can I contribute this extension back to Sprache?

**Comment by IanWold** [comment]
Take a look at [IComment](https://github.com/sprache/Sprache/blob/develop/src/Sprache/IComment.cs) and [CommentParser](https://github.com/sprache/Sprache/blob/develop/src/Sprache/CommentParser.cs).

Can your solution be integrated with these in such a way that it doesn't break existing code using IComment? Perhaps IComment could be replaced by your logic?

So long as we're not breaking existing code or adding redundancy I support this proposal!

**Comment by yallie** [comment]
Hi @IanWold , I'm aware of the `CommentParser` (actually, my solution uses it behind the scenes).
So it doesn't replace `IComment` and doesn't affect any existing code, it just adds this leading/trailing
comment notion.

**Comment by nblumhardt** [comment]
Sounds good, if these two things can be neatly unified.

Is it possible, for example, that `Commented()` could accept a comment parser, or somehow otherwise expose how it ties in to permit modification of the comment syntax?

**Comment by yallie** [comment]
>Is it possible, for example, that Commented() could accept a comment parser, 
>or somehow otherwise expose how it ties in to permit modification of the comment syntax?

Yes, exactly. It accepts an optional comment parser, or a comment parser provider,
so the comment syntax is customizable.

The only thing I'm missing from `IComment` is that it doesn't distinguish between 
parsed comments (both single-line and multi-line comments are returned as strings). 
Also, some languages have more than two kinds of comments.

But that's another story :)

**Comment by yallie** [comment]
Hello!

Anything I can do to help reviewing my pull request #102?

**Comment by nblumhardt** [comment]
Sorry about the lag, @yallie. The PR looks good; it's only apprehension about adding more code to support that's holding me up - it takes a while to get into the right head-space to think though changes in this project :-) Pushing it through now.

**Comment by yallie** [comment]
Thanks a lot Nicholas! 👍 
No worries about the lag!
