### ISSUE TITLE
When can we expect a new Version?

### ISSUE THREAD

**Issue by Fruchuxs** [sprache/Sprache#103]
Since 2016 (2.1.0) there are some nice Changes in Sprache (e.g. XOptional), I want to use. But there are no new Versions available as NuGet Package. I can build it by myself, but it seems a new Version is near?

**Comment by nblumhardt** [comment]
Thanks for reaching out. `XOptional()` is not yet merged, but you can grab the code from here and use it without recompiling Sprache: https://nblumhardt.com/2015/11/aggregate-queries-in-seq-part-3-an-opportunistic-parser/

The 2.1.0 build only updates the tooling to the `dotnet` toolchain, so isn't ready for a release just yet.

Thanks!

**Comment by nblumhardt** [comment]
Hmm - actually, looks like the most recent master builds failed: https://ci.appveyor.com/project/Sprache/sprache/build/13

(This still doesn't contain `XOptional()`, however).

Will fix now. Thanks again :-)

**Comment by nblumhardt** [comment]
2.1.2 is now on NuGet

**Comment by Fruchuxs** [comment]
Your Code doesn't works, cuz the Template Parameter is missing and the classes you are use are internal now.

**Comment by nblumhardt** [comment]
Code sample fixed, thanks for the heads-up 👍
