### ISSUE TITLE
ParseException should expose position

### ISSUE THREAD

**Issue by cptjazz** [sprache/Sprache#105]
Currently, a ``ParseException`` does not explicitly expose the ``Position`` where the parsing error occurred. It is only implicitly available in the message string. This is not very useful when one wants to deal with parsing errors and wants to indicate to the user *where* in the input the error occurred.

The ``ParseException`` should expose a ``Position`` (and maybe length) of the token where the parser was unable to accept the input.

**Comment by nblumhardt** [comment]
Thanks for the suggestion, sounds worthwhile 👍

**Comment by daveMueller** [comment]
I made pull request for this. Would be cool if somebody will review and approve or reject?

**Comment by IanWold** [comment]
Resolved by #127
