### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by blue865** [sprache/Sprache#106]
Please try to enhance the performance especially of recursive parsing. For bigger files Sprache becomes pretty unusable.

Other this could be adding some sort of progress bar support - an ability to access parsed snippets or something. This would to some extend help with the performance problem.

**Comment by nblumhardt** [comment]
@blue865 thanks for getting in touch. Perf improvements are welcome, if you're able to do some targeted profiling and provide test cases, but it's unlikely we'll get traction on a generic "perf" ticket like this so I'll close it for now. Thanks!
