### ISSUE TITLE
Support for ReadOnlySpan<char> as an input

### ISSUE THREAD

**Issue by pamidur** [sprache/Sprache#113]
So now as we've got new super fast Span<T> types, I guess it would be nice to have it support in Sprache.
This will prevent unnecessary allocation and boost performance in cases where parser used often.

**Comment by nblumhardt** [comment]
Thanks for the suggestion. This would be interesting to tackle, but there are a _lot_ of allocations to get rid of (and alternative parsing strategies to explore) before I think the effect of `ReadOnlySpan<char>` will be visible. Currently, Sprache uses the `Input` type to work over the input source, so span support wouldn't result in an immediate en masse improvement.

Open to PRs that demonstrate a perf boost, but not thinking of actively pursuing this, so closing for now. Cheers!
