### ISSUE TITLE
How to return Parse fail result?

### ISSUE THREAD

**Issue by 3da** [sprache/Sprache#118]
for example I have switch:
public static Parse<...>(string keyWord)
{
                    case "aaa":
                        return Parse......;
                    case "bbb":
                        return Parse.....;
                    default:
                        return Fail.....;
}

I can throw Exception but it will break all parsing and ignore other parsing paths.

**Comment by IanWold** [comment]
Success and failure is implemented by `Result` (https://github.com/sprache/Sprache/blob/develop/src/Sprache/Result.cs). The `Parser.TryParse` method returns an `IResult`, so I imagine your example could look like the following:

```c#
case "aaa":
    return someParser.TryParse(someString);
case "bbb":
    return someOtherParser.TryParse(someString);
default:
    return Result.Failure<T>(someRemainder, "There was a failure!", someExpectations);
```

**Comment by 3da** [comment]
I tried that but there was compilation error "cannot convert IResult<> to Parser<>.
This probably works only in following manner (inside delegate method body):
`
return i =>
{
                return Result.Failure<>(...);
            };
`

But not when I need return Parser<T>

**Comment by IanWold** [comment]
You didn't mention you need to return Parser. Could you please paste the entire method?

**Comment by IanWold** [comment]
You are correct that this is how you should return a failed result: `return i => Result.Failure(...)`

**Comment by 3da** [comment]
> You are correct that this is how you should return a failed result: `return i => Result.Failure(...)`

Thanks! I understand how it is possible to implement, but it will look not very nice. Because all other parts return Parser<>. 
Is it possible to add something to Parse class to avoid ` return i => Result.Failure(...) ` ?

**Comment by IanWold** [comment]
You cannot extend the `Parse` class because it is a public static partial class, but you could add your own method to it and compile Sprache yourself. I would imagine the following should get you close:

```c#
public static Parser<T> Fail(string message)
{
    return i => Result.Failure(i, message, null);
}
```

Parse does currently contain `Return` which succeeds immediately (https://github.com/sprache/Sprache/blob/develop/src/Sprache/Parse.cs#L538), which I consulted to write the code above.

**Comment by 3da** [comment]
That's what I am talking about. Of course I can do it in my own fork. But why you think it shouldn't be implemented in main repository?

**Comment by IanWold** [comment]
It is not the case that I do not think it shouldn't be implemented in the library. If you and others need it then I would support adding it to Sprache.

If you want to open a discussion as to whether it should be added, I would recommend starting a new issue or submitting a PR, as this issue appears to be asking for help on using the framework.
