### ISSUE TITLE
Is there any documentation?

### ISSUE THREAD

**Issue by johnny0914** [sprache/Sprache#122]
I have really a hard time to figure out how to do thing with Sprache.
Is there any documentation?
Something like https://github.com/otac0n/Pegasus/wiki/Syntax-Guide
E.g. how to check if the cursor is before "foo" without changing the cursor?

**Comment by johnny0914** [comment]
How to return different things when an optional parsing rule succeeds or fails?

        static readonly Parser<string> item=
            from g in Parse.Optional(id)
            select (if g succeed return a else return b );

**Comment by 3da** [comment]
> E.g. how to check if the cursor is before "foo" without changing the cursor?
I guess "Parse.Preview" is for this.

**Comment by 3da** [comment]
> How to return different things when an optional parsing rule succeeds or fails?

Use "Parse.Or" for this.

**Comment by johnny0914** [comment]
I got it:

        static readonly Parser<string> item=
        from g in Parse.Optional(id)
        select g.IsEmpty ? b : a;

**Comment by johnny0914** [comment]
Does the order of parser matter? Like the example blow?


        public static readonly Parser<string> macro_argss = macro_args.Many().Return("a");
        public static readonly Parser<string> macro_args = Parse.String("a").Text();
