### ISSUE TITLE
Many and OR remainder

### ISSUE THREAD

**Issue by johnny0914** [sprache/Sprache#123]
In the Many methode the part about remainder is annoying.  I have an optional parser and if it fails it returns a default but `remainder.Equals(r.Remainder)` does not allow that. How to get rid of that?

https://github.com/sprache/Sprache/blob/a286cb382e1daeb721df94b3381bc78659dcda16/src/Sprache/Parse.cs#L260-L261

https://github.com/sprache/Sprache/blob/a286cb382e1daeb721df94b3381bc78659dcda16/src/Sprache/Parse.cs#L432-L433

**Comment by johnny0914** [comment]
_Originally posted by @nblumhardt in https://github.com/sprache/Sprache/issues/52#issuecomment-238513424_

**Comment by nblumhardt** [comment]
Hi @johnny0914 - as mentioned in the linked comments, this one needs some serious investigation and a plan, without which it's tough to move forward. I think we should close as per the other ticket, until there's a concrete proposal for improvement. Thanks!

**Comment by johnny0914** [comment]
I think it should be changed. If the combinator is successful even if it did not consume any char, is because **it was intended to do so**. To get the current setting you can use span and check if the start and end are the same.

**Comment by johnny0914** [comment]
I think it should be changed. If the combinator succeeds even if it did not consume any char, it means **it was intended to do so**.  You can get the current way by using span and checking if the start and the end are the same.
