### ISSUE TITLE
How do I make a parser return a string when it is already returning something else?

### ISSUE THREAD

**Issue by johnny0914** [sprache/Sprache#124]
E.g. 

       string input = "aaa";

       public static readonly Parser<string> parsea =
                from x in Parse.AnyChar.Preview()
                from a in Parse.Char('a')
                select "g";

        public static readonly Parser<string> parseax =
                from ab in parsea.Many() select string.Join("", ab.ToArray());

This would give `ggg`, but I want the string `aaa`

Does Sprache provide this feature?
Somethin like [this from Pegasus](https://github.com/otac0n/Pegasus/wiki/How-Do-I...-%3F#how-do-i-make-an-expression-return-a-string-when-it-is-already-returning-something-else)
or `$ expression` in PEG.js

**Comment by nblumhardt** [comment]
Something like your combinator above is the way to go 👍 (Superpower calls this `Span.MatchedBy()`, FWIW.)
