### ISSUE TITLE
Parse.Ref use case

### ISSUE THREAD

**Issue by johnny0914** [sprache/Sprache#126]
When do we have to use `Parse.Ref`?
I looked at the exmples but could not understand the use case of `Parse.Ref`.
Does it make the parsing faster or slower?
Does it save space?

**Comment by IanWold** [comment]
You can use Parse.Ref when you need to construct a circular dependency between two parsers. For a real-world example, I use it in my [JSON Parser](https://github.com/IanWold/SpracheJSON/blob/master/SpracheJSON/JSONParser.cs#L124) You cansee that `JValue` is dependent on both `JObject` and `JArray`, and both of those are also dependent on `JValue` in turn.

**Comment by johnny0914** [comment]
In the following code `parseArg1` and `parseArg2` call each other. It works without `Parse.Ref`. 

       public static readonly Parser<string> parseArg1 =
                from a in Parse.Char('{')
                from b in parseArg2.Or(parseArg).Or(Parse.String(".").Text())
                from c in Parse.Char('}')
                select a.ToString()+b+c.ToString();



        public static readonly Parser<string> parseArg2 =
                from a in Parse.Char('[')
                from b in parseArg1.Or(parseArg).Or(Parse.String(".").Text())
                from c in Parse.Char(']')
                select a.ToString() + b + c.ToString();


        string input = "{[{[{.}]}]}";
        var parsed = XmlParser.parseArg1.Parse(input);
Isn't this a circular dependency?
Would you use `Parse.Ref` in this example?

**Comment by brodny** [comment]
It also helps to deal with field initialization order - a change in the order can cause the code to stop working by throwing NullReferenceException/ArgumentNullException. Referencing a parser via Parse.Ref() can help to deal with potentially hard to find errors. I got struck by it when rewriting the examples. You can see more details in my lessons learned file - <https://github.com/brodny/sprache-playground/blob/main/LessonsLearned.md>.
