### ISSUE TITLE
Exception when run the same sub-parser in different places.

### ISSUE THREAD

**Issue by 3da** [sprache/Sprache#129]
What's the reason of this line?
`
throw new ParseException(i.Memos[p].ToString());
`

It broke my parser. When I changed it to 
`
return (IResult<T>)i.Memos[p];
`
everything started work as expected.

**Comment by nblumhardt** [comment]
Hi! We might need some more context - where's that line, and what is your parser doing? What's the exception look like? Cheers!

**Comment by 3da** [comment]
Hello.
This line is here:
https://github.com/sprache/Sprache/blob/a286cb382e1daeb721df94b3381bc78659dcda16/src/Sprache/Parse.cs#L391

**Comment by r1sc** [comment]
I experienced the same error. My case was using Ref inside an Or like .Or(Parser.Ref(() => ...
This threw an exception along the lines of "Successful parsing of <correct type that should be returned>".

Modifying the above line fixes the error (i.e. no longer throws exceptions on successful parsing).

**Comment by r1sc** [comment]
Why was this closed? The above error has not been fixed?

**Comment by r1sc** [comment]
This is what I had to do to allow all tests to pass (at the position @3da provided):

```
if (i.Memos.ContainsKey(p))
{
    var pResult = i.Memos[p] as IResult<T>;
    if (pResult.WasSuccessful)
        return pResult;
    throw new ParseException(pResult.ToString());
}
```

**Comment by nblumhardt** [comment]
Great, thanks @r1sc - think I misread your reply above, when I closed this :+1:
