### ISSUE TITLE
Make Some and None public and maybe add Select to OptionExtensions

### ISSUE THREAD

**Issue by delreluca** [sprache/Sprache#137]
I’m handling some nested IOption results. Unfortunately `OptionExtensions` does not offer `Select`, so I wanted to write that extension myself.

Unfortunately since `Some`/`None` are internal I would have to implement my own classes. This seems like unnecessary overhead to overcome the .IsDefined and .Get cascades.

Can we make at least Some and None public? Then I can do

```cs
public static IOption<U> Select<T>(this IOption<T> o, Func<T, U> f) => o.IsDefined ? (IOption<U>) new Some<U>(f(o.Get())) : new None<U>();
```

Many thanks

**Comment by delreluca** [comment]
See PR #148

**Comment by nblumhardt** [comment]
Closing with #148 in; can revisit this if there are still significant gaps anywhere. Thanks @delreluca 👍
