### ISSUE TITLE
An assembly with a strong name is required

### ISSUE THREAD

**Issue by Hoschi1982** [sprache/Sprache#140]
Hi there 

I want to use Sprache referenced from an strong named assembly.

No I get an error because the assembly has not a strong name signature.
Is it possible to get the assembly in a short time with a strong name?

thanks a lot !!

**Comment by jzabroski** [comment]
Add a package reference in your project to StrongNamer package. It is like
a shot of Jameson in your Turkey eggnog.

**Comment by Hoschi1982** [comment]
thanks i will try it
