### ISSUE TITLE
Parsing floating number?

### ISSUE THREAD

**Issue by Shadowblitz16** [sprache/Sprache#143]
how exactly would I parse a floating number with a optional floating point?

this right here isn't valid...
```cs
        Parser<string> Num =
            from frst in Parse.Number.AtLeastOnce()
            from plac in Parse.Char('.').Once().Optional()
            from last in Parse.Number.AtLeastOnce()
            select frst + plac + last;
```
and I can't add `Text()` at the end of the `Parse.Char('.').Once().Optional()`

**Comment by nblumhardt** [comment]
`Parse.Decimal` exists to cover this 👍
