### ISSUE TITLE
SpracheLite idea

### ISSUE THREAD

**Issue by Shadowblitz16** [sprache/Sprache#144]
so I had an idea to make sprache more readable.
basicly it would be either a low level (rewrite) or a wrapper over sprache

basicly it would split string operations into 3 categories 
-value
-operation
-operator

for example
values functions would be like so..
```cs
ParseValue Parse.Char (char   n); //requires a char of n
ParseValue Parse.Chars(char[] n); //requires one of chars of n
ParseValue Parse.WhiteSpace();    //requires whitespace
```

operations would be like so..
```cs
ParseOperator ParseValue.AtLeast(int times);  //Must occer at least "times" times
ParseOperator ParseValue.AtMost (int times);  //Must occer at most "times" times
ParseOperator ParseValue.Until     (char   c);//Must occer until "c"
ParseOperator ParseValue.UntilAnyOf(char[] c);//Must occer until any of "c"
ParseOperator ParseValue.UntilAllOf(char[] c);//Must occer until all of "c"
ParseOperator ParseValue.UntilEnd();          //Must occur until end
```

and operators would be like so..
```cs
string ParseOperator.AndRequire(); //must require a left side ParseOperator and right side ParseOperator 
string ParseOperator.XorRequire(); //must require a left side ParseOperator xor right side ParseOperator 
string ParseOperator.OrRequire();  //must require a left side ParseOperator or right side ParseOperator 
string ParseOperator.AndOptional();//a optional left side ParseOperator and right side ParseOperator 
string ParseOperator.XorOptional();//a optional left side ParseOperator xor right side ParseOperator 
string ParseOperator.OrOptional(); //a optional left side ParseOperator or right side ParseOperator 
string ParseOperator.End();        //End
```

and it would look this.
```cs
        Parser<string> Number =
            from frst in Parse.Chars(new char[10] {0,1,2,3,4,5,6,7,8,9}).AtLeast(1).AndOptional()
            from plac in Parse.Char('.').AtLeast(1).AndRequire()
            from last in Parse.Chars(new char[10] {0,1,2,3,4,5,6,7,8,9}).AtLeast(1).End()
            select frst+plac+last;
```
although its longer, its easier to understand, and is more like English.

this is just an idea and I don't actually know how it would work for things like c like goto statements
which goto a line of code, however I think this idea could be improved and would make things easier to understand and document.

**Comment by nblumhardt** [comment]
Thanks for posting your idea. Currently, there's no maintainer bandwidth available to consider adding these things to Sprache, but if you end up building/publishing it separately it would be interesting to see 👍 

I'm doing a round of issue-tracker clean-up and will close this as we don't plan to take action on it currently. Thanks!
