### ISSUE TITLE
The change from #153 included not needed dependencies for .net Standard 2.x, those are only required for ns1.x.

### ISSUE THREAD

**Issue by MagicAndre1981** [sprache/Sprache#162]
The change from #153 included not needed dependencies for .net Standard 2.x, those are only required for ns1.x.

![image](https://user-images.githubusercontent.com/8274816/94520655-ee042e00-022c-11eb-818d-f5e5fcb69e47.png)

This includes a lot of old packages which are not needed at all.

Can this be fixed?

_Originally posted by @MagicAndre1981 in https://github.com/sprache/Sprache/issues/152#issuecomment-700477098_

**Comment by nblumhardt** [comment]
Thanks for the note, not sure how that one slipped past me! :-) ... A PR would be great if anyone is able to look into this 👍

**Comment by MagicAndre1981** [comment]
ok, I created a PR #163 when I installed my test version in my Xamarin.Forms Android project with packages.config, I no longer get offered to install the other packages.

**Comment by nblumhardt** [comment]
Fixed in #163

**Comment by MagicAndre1981** [comment]
> Fixed in #163

when will the stable version be released?

**Comment by nblumhardt** [comment]
Just created release PR #167 - thanks @MagicAndre1981 :+1:

**Comment by MagicAndre1981** [comment]
> Just created release PR #167 - thanks @MagicAndre1981

the new stable release was never published and the PR failed to build 🤔

**Comment by nblumhardt** [comment]
Looks like we need to make some updates to the CSPROJ. It's surprising that `sl5` is still a supported target in there! Time to modernize :-)

**Comment by MagicAndre1981** [comment]
> It's surprising that `sl5` is still a supported target in there! Time to modernize :-)

I created a new issue for this to track.
