### ISSUE TITLE
Line number

### ISSUE THREAD

**Issue by OmidID** [sprache/Sprache#165]
Is it possible to get the current line number?

```csharp
        static readonly Parser<Node> NodeParser =
            from first in Parse.Char('{').Token()
            from item in Parse.Ref(() => ItemNode).Many()
            from last in Parse.Char('}').Token()
            select new Node(item, **** LINE NUMBER FROM SOURCE ****);
```
I using Sprache to parse a template and generate a code and I want to make the debug easier, that why I need to add [#line](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/preprocessor-directives/preprocessor-line) to each part of the generator.

As an example, create a WPF project build it then open the project directory in `obj/debug/[net472|net5|...]/` you can find generated files. You can open `Window1.g.cs` to see how generated code referring to the xaml file

**Comment by yallie** [comment]
Hi @OmidID,

use `Span()` method to get the source code location.

See the example here: ParseTests.cs, [line 555](https://github.com/sprache/Sprache/blob/develop/test/Sprache.Tests/ParseTests.cs#L555).

Something like this:

```csharp
        static readonly Parser<Node> NodeParser =
            from first in Parse.Char('{').Token().Span()
            from item in Parse.Ref(() => ItemNode).Many()
            from last in Parse.Char('}').Token()
            select new Node(item, first.Start.Line);
```
