### ISSUE TITLE
Time to modernize csproj and drop old TargetFramework entries

### ISSUE THREAD

**Issue by MagicAndre1981** [sprache/Sprache#172]
Looks like we need to make some updates to the CSPROJ. It's surprising that `sl5` is still a supported target in there! Time to modernize :-)

_Originally posted by @nblumhardt in https://github.com/sprache/Sprache/issues/162#issuecomment-857194276_

**Comment by MagicAndre1981** [comment]
Which targets should be supported? Only .net standard 2.x?

**Comment by nblumhardt** [comment]
Thanks! 👍 

I think `netstandard2.0` and `net5.0` would be my picks; it's largely a matter of opinion, though.

For `netstandard2.0`, null checking can be enabled with some fiddling around, and this would keep (newer) .NET Framework versions supported, while not requiring .NET Framework to be installed during development.

`net5.0` has a lower deployment footprint and will be a better fit for newer apps.

**Comment by MagicAndre1981** [comment]
.net core 3.1 is LTS and has netstandard2.1 support. Does this bring any benefit over netstandard2.0 when using the lib in .net core 3.1 project?

**Comment by nblumhardt** [comment]
Would guess there's some modest benefit, but, also some advantages to starting fresh without additional targets to carry forwards :-)

**Comment by MagicAndre1981** [comment]
I would go with `netstandard2.0` (classic .net framework, Xamarin.Android with VS2017 and UWP), `netstandard2.1` (Xamarin.Android with VS2019 and .net core 3.1) and `net5.0` to have best compatibility.

**Comment by nblumhardt** [comment]
I could live with that! :-) 👍

**Comment by MagicAndre1981** [comment]
Do you already had some time?

**Comment by nblumhardt** [comment]
Thanks for the nudge! Sorry, no, not looking good for the next few weeks - all help appreciated.

**Comment by MagicAndre1981** [comment]
> all help appreciated.

I made a quick fix in PR #173 .

You should look later in code for old hacks that can be removed.

**Comment by MagicAndre1981** [comment]
what about .net 6 support and final release of version 3 of the lib? @nblumhardt
