### ISSUE TITLE
I cannot use Or with ConditionalExpression

### ISSUE THREAD

**Issue by phatnguyentit** [sprache/Sprache#180]
```
static readonly Parser<Expression> _greaterThanLogical =
         from left in _expr
         from greater in Parse.String(">=")
         from right in _expr
         select Expression.GreaterThanOrEqual(left, right);
```

        static Parser<Expression> _condition =
            from openParen in _groupStart
            from logicalConjunction in _greaterLogical.Or(_greaterThanLogical).Or(_smallerLogical).Or(_smallerThanLogical).Or(_equalLogical)
            from trueSplitter in _comma
            from trueOperand in _expr
            from falseSplitter in _comma
            from falseOperand in _expr
            from endIf in _groupEnd
            select Expression.Condition(logicalConjunction, trueOperand, falseOperand);

Only the first condition _greaterLogical is affected
Can someone help a bit on this issue?

**Comment by phatnguyentit** [comment]
I'm building a parser for the If statement like Excel, for example: If(2>3, 50, 70)
And the condition is built by the ConditionalExpression, it may be a "GreaterThan" or "GreaterThanOrEqual", etc..
But with the given code, just the first condition is matched in the 'Or' sequence

**Comment by nblumhardt** [comment]
Hi @phatnguyentit - you can work around this by trying the most-matching parser first:

```csharp
    _greaterThankLogical.Or(_greaterLogical).Or(...
```

HTH!

**Comment by phatnguyentit** [comment]
Hi @nblumhardt, thanks for your suggestion. I have tried that before and nothing different
But I just update Sprache to the latest version and it works 👯
