### ISSUE TITLE
Left recursive grammar

### ISSUE THREAD

**Issue by speps** [sprache/Sprache#22]
I'm trying to implement a complicated grammar and found myself in a blocking situation.

    type:
        simple-type 
        nullable-type
        struct-type
        enum-type
    nullable-type:
        type   ?

Something like this throws an exception in the Parse.Ref I'm using to reference the Type parser in the NullableType parser. I am wondering if this at all possible, it looks like from the tests that it's not implemented yet. Also it seems other similar parsers (parsley) claim they handle "infinite look-ahead" parsers.

My question is how much is needed in Sprache to handle this kind of grammar? Is it at all possible? I don't mind doing the work but I want confirmation first before looking more into it. Thanks.

**Comment by sky-dev** [comment]
I'm experiencing the same difficulty.  How would one refactor this code to be right recursive and also support multidimensional arrays?

ex. int[][][][][]

type:
    simple-type 
    array-type
    struct-type
    enum-type
array-type:
    type   []

**Comment by sergiusignacius** [comment]
In my case I actually didn't have a standalone rule for the Array Type. Here's what I did:

```C#
from typ in (simple | struct | enum)

from arrays in Parse.String("[]").Token().Text().Many()

select(
      arrays.Aggregate(typ, (t, elem) => new ArrayType(t))
);```

Hope it helps.

Cheers,
