### ISSUE TITLE
Ignoring comments with Sprache

### ISSUE THREAD

**Issue by sergiusignacius** [sprache/Sprache#29]
Hi Nicholas,

First of all, Sprache is awesome, great job! :)

I'm using it to build a TypeScript parser, to parse definition signatures. I was wondering if I could have your input on how I could write a rule to ignore comments (// or /**/). In ANTLR, e.g., comments are treated as whitespace. Is there a way to do that?

Thanks in advance!

Cheers,

**Comment by nblumhardt** [comment]
Closed via #48.
