### ISSUE TITLE
ChainOperator succeeds even when the operator is not present.

### ISSUE THREAD

**Issue by TorbenRahbekKoch** [sprache/Sprache#30]
Consider the following parser and two calls to it:

````
       Parser<char> A =
            Parse.ChainOperator(
                Parse.String("op").Text().Token(),
                Parse.Chars("ab"),
                (a, b, c) => b);
            
            var resulta = A.Parse("a op b");
            var resultb = A.Parse("a po b");

````
Both calls succeed, which is surprising. The first call *should* succeed, the second definitely should *not*, but resultb ends up being 'a' - just as resulta does.

**Comment by nblumhardt** [comment]
Hi @TorbenRahbekKoch - sorry about the delay on replying; your parser is missing the `.End()` combinator to assert end-of-input, so it'll just match as much as it can before returning a result.
