### ISSUE TITLE
What is the best way to parse both decimal and integer tokens?

### ISSUE THREAD

**Issue by Thecentury** [sprache/Sprache#33]
Hi!

I would like to be able to parse both decimal and integer numbers, producing different tokens in each case.

When one string can be parsed both as integer and decimal, integer should be preferred.

To archive this, I have created this method, that chooses from two parse results one that has consumed more long piece from source input:

```csharp
public static Parser<T> LongestOf<T>( Parser<T> first, Parser<T> second )
{
	return input =>
	{
		var firstResult = first( input );
		var secondResult = second( input );

		if ( firstResult.WasSuccessful && secondResult.WasSuccessful )
		{
			if ( firstResult.Remainder.Position >= secondResult.Remainder.Position )
			{
				return firstResult;
			}
			else
			{
				return secondResult;
			}
		}

		if ( firstResult.WasSuccessful )
		{
			return firstResult;
		}

		return secondResult;
	};
}
```

And then I'm using it to combine int and decimal parsers like this:

```csharp
LongestOf( IntParser, DecimalParser )
```

Is it correct way to reach my needs?

**Comment by nblumhardt** [comment]
@Thecentury grabbing the source for `Parse.Decimal` (it's only a few lines) will hopefully give you the starting point you need for this; feel free to reopen/post if you still need a hand. Cheers!
