### ISSUE TITLE
Backport Sprache to .NET 3.5 is easy.

### ISSUE THREAD

**Issue by mattiasw2** [sprache/Sprache#34]
If you want to use this library in .NET 3.5, add these to Parse.cs and change "." to "_" in about 6 places.

		// backported to .NET 3.5
        public static string string_Join(string sep, char[] value)
        {
            var length = value.Length;
            string[] tmp = new string[length];
            for (int ii = length - 1; ii >= 0; ii--)
            {
                tmp[ii] = new string(value[ii], 1);
            }
            return string.Join(sep, tmp);
        }

        public static string string_Join(string sep, IEnumerable<string> value)
        {
            return string.Join(sep, value.ToArray());
        }

**Comment by nblumhardt** [comment]
Thanks for posting this. Closing as we're not likely to make this port in the project itself, but your comments are valuable for anyone Googling this - hopefully they will still find them here. All the best!
