### ISSUE TITLE
Csv Example - How To Trim Spaces

### ISSUE THREAD

**Issue by markgmarkg** [sprache/Sprache#44]
Hi,

In the CSV sample, the resulting cell content may include leading or trailing white spaces.
What should be a right way to handle their removal?

Now cell literals are accumulated with LiteralCellContent parser
```c#
static readonly Parser<char> LiteralCellContent =
            Parse.AnyChar.Except(CellSeparator).Except(Parse.String(Environment.NewLine));
```
... and then the cell content returns with Cell parser
```C#
static readonly Parser<string> Cell =
            QuotedCell.XOr(
            LiteralCellContent.XMany().Text());
```

Thank you
Mark

**Comment by markgmarkg** [comment]
Worked perfectly :)
Thank you

**Comment by nblumhardt** [comment]
Hi @markgmarkg - @MarkJPerry is correct, `Token()` is what you need here, but it's possible something else in the example is thwarting it. I'll close this since it's quite old now, but feel free to reopen and post a complete sample if you still need a hand with this. Cheers!
