### ISSUE TITLE
Example of using unary operators such "!" or not

### ISSUE THREAD

**Issue by fritzcoder** [sprache/Sprache#47]
I am using Sprache successfully with all conditional operators that are binary however, I am trying to use "!" and can't seem to get it to work. An example of using unary would be great! 

Thanks!

**Comment by nblumhardt** [comment]
Hi Fritz - not sure I can point you to any existing examples, but a post on StackOverflow might track down some? Will close this since we're not able to address this with an issue fix. Cheers!
