### ISSUE TITLE
A PCL version of Sprache that supports WP8.1

### ISSUE THREAD

**Issue by gordonwatts** [sprache/Sprache#49]
It looks like the current version of Sprache in nuget does not support WP 8.1 (I get from nuget an incompatibility warning when I try to install it). Any chance we could get a version that is re-targeted to include that platform?

    Could not install package 'Sprache 2.0.0.45'.
    You are trying to install this package into a project that
    targets 'portable-net40+win+wpa81', but the package does not contain
    any assembly references or content files that are compatible with that
    framework. For more information, contact the package author.

**Comment by gordonwatts** [comment]
Someone else has already posted a version to help with this situation: http://www.nuget.org/packages/CGenT.Sprache/ - it has strong naming and is also re-targeted.

**Comment by SuperJMN** [comment]
Me too!

**Comment by nblumhardt** [comment]
PRs gratefully accepted on this front. Not sure if it's just a matter of adding `wpa81` to the list of supported profiles, but should be pretty simple. Cheers!

**Comment by nblumhardt** [comment]
Will cover this in #74
