### ISSUE TITLE
Introduce parsing context

### ISSUE THREAD

**Issue by i-sinister** [sprache/Sprache#54]
I need 'context-dependent' parser, that would check collection, provided at parsing time, if token is allowed. To achieve this i thought of extending Input class to Input<T>:
```
public class Input<TContext> : Input
{
...
public TContext Context { get; private set; }
...
}
```
In my parser I would cast input to desired type and failed if context is not available. However in current implementation Input has internal constructor so I have to 'reimplement it'.

Can you please make Inputs second ctor protected add/or Input&lt;TContext&gt; (please consider co/contra variance)?

Also Parse/TryParse methods could accept class, derived from IInput, not only string

**Comment by nblumhardt** [comment]
Hello!

Have you considered making your parser non-static, e.g. within a closure, to achieve this?

```
csharp
var context = new SomeContext();

var thing = Parse.String("thing");

var other = thing.Where(t => /* context available via closure */);

// etc.
```

**Comment by i-sinister** [comment]
Thank you for response and sorry for answering lateI abandoned Sprache usage because found easier way to do what I need (without parsing input string) so I'm closing issue. Later if I'll need it again I'll try you proposal. Thank you.
