### ISSUE TITLE
How can I match the end of file?

### ISSUE THREAD

**Issue by gordonwatts** [sprache/Sprache#55]
I have a parser that is supposed to look at the complete text of a file:

        public static Parser<JobFile> ParseJobFile
            = from rid in (
                  ParseJob.ParseAs<Action<JobFile>, AtlasJob>(r => (JobFile f) => f.Jobs = f.Jobs.Append(r))
                  .Or(ParseSubmissionMachine.ParseAs<Action<JobFile>, SubmissionMachine>(r => (JobFile f) => f.machines = f.machines.Append(r)))
                  .Or(CommentLine.ParseAs<Action<JobFile>, string> (line => (JobFile f) => { }))
                  ).Token().Many()
              select AsJobFile(rid);

If my text file contains a syntax error, it does not fail (an empty file is also a legal file). If my file contains good lines and some bad ones, it will parse fine and record results till the first bad line.

I tried replacing Many by XMany, and that works as long as the new line starts with something sensible and the mistake comes later on. So, if the first token after the last complete line parse is invalid, it will again give up.

So, I'd like to force it to parse every single character in the file and report any errors if it fails. I figured if I added a "from eof in Parse.EOF" or similar, I'd be set. But I'm not sure how to accomplish that.

**Comment by nblumhardt** [comment]
Try: `YourParser.End()` - it's something like "at end of file" or "then end of file" and covers exactly this case. Thanks for the note!
