### ISSUE TITLE
Newbe Question: Parsing a String

### ISSUE THREAD

**Issue by jayonsoftware** [sprache/Sprache#57]
I want to get a list of words from a given string

Parser<string> Text = Parse.WhiteSpace.Many().Text();
var id = Text.Parse("Abc Bcd Cef");

The above is wrong. What is the correct way to split a string based on space. 

Thanks

Jay

**Comment by nblumhardt** [comment]
Hi Jay,

Here's one way to go, let me know what you think:

```csharp
var words = Parse.LetterOrDigit
    .AtLeastOnce()
    .Text()
    .Token()
    .Many()
    .End();

var result = words.Parse("Abc Bcd Cef");
foreach (var word in result)
    Console.WriteLine(word);
```

Prints:

```
Abc
Bcd
Cef
```
