### ISSUE TITLE
Build that works for coreclr

### ISSUE THREAD

**Issue by nguyenm100** [sprache/Sprache#61]
Can we get a published build to nuget that works with coreclr?  I'd like to run it on Unix.

I believe the best way to do this (for coreclr rc1) is to include a project.json and include something like:

  "frameworks": {
    "dotnet5.4": {
      "dependencies": {
        "Microsoft.CSharp": "4.0.1-beta-23516",
        "System.Collections": "4.0.11-beta-23516",
        "System.Linq": "4.0.1-beta-23516",
        "System.Runtime": "4.0.21-beta-23516",
        "System.Threading": "4.0.11-beta-23516",
        "System.Text.RegularExpressions": "4.0.11-beta-23516"
      }
    }
  }

http://stackoverflow.com/questions/31539341/project-json-definition-dnx451-vs-dotnet-4-51
https://github.com/dotnet/coreclr

**Comment by DaveVdE** [comment]
I'll second that. If it's trivial I might even fork and set up my own package for internal use.

**Comment by nblumhardt** [comment]
Howdy! Now that the RTM of the Core CLR runtime is close, this would be nice. There's an example showing how this can all fit together using AppVeyor in the Serilog repo, https://github.com/serilog/serilog - the same layout/scripts would just about cover Sprache too.

A PR would be great, if anyone has the opportunity. Keen to move forward on this but short of time in the next few weeks.

**Comment by DaveVdE** [comment]
I'm giving it a shot right now. 

Would you also like to move the tests to xUnit as in Serilog?

**Comment by nblumhardt** [comment]
Thanks @DaveVdE - that's awesome. I don't have a strong preference regarding the tests - if NUnit is sufficient on .NET Core I'm happy leaving things as-is, but a switch to xUnit is fine if it makes things any easier.

**Comment by DaveVdE** [comment]
Okay I checked this morning, but porting the tests to xUnit is pretty ugly (there's no `Assert.Fail` for instance, that seems to be used a lot).

My main concern is being able to use the CLI test runner, but I have to check if that's possible or not with NUnit. I know I started to write my tests in xUnit a few weeks ago when we started our project on top of .NET Core.

**Comment by droyad** [comment]
@DaveVdE It is possible, checkout https://github.com/OctopusDeploy/CSProjToXProj/blob/master/src/Tests/project.json to see how to set it up.

If you need any help porting, let me know.

**Comment by nblumhardt** [comment]
`2.1.0-develop-00005` now on NuGet supports .NET Core.
