### ISSUE TITLE
How can you parse something like this?

### ISSUE THREAD

**Issue by icaras1907** [sprache/Sprache#62]
Hallo, 

I got stucked at some point and need some help.
I have written a commentparser, newlineparser and itemparser to parse following information

; here is my first comment
/r/n
item1=parameter1;parameter2

Here is how my parser looks like;
        static readonly Parser<MyItem> ItemLine =
            from empty1 in NewLine.Many().Optional()
            from comment1 in SingleLineComment.Many().Optional()
            from keyname in KeyContent.Except(LeftBracket).Except(NewLine)
            from parameters in KeySeparator.Or(ParameterSeparator).Then(_ => ItemContent).Many()
            from terminator in NewLine
            from comment2 in SingleLineComment.Many().Optional()
            select new MyItem(keyname, parameters);

The problem is if the number of the comment lines and empty lines are changing in the text, than my parser is not working.

For example if I have something like this, than it is not working.

; first comment
/r/n (first empty line)
;second comment
/r/n (second empty line)
/r/n (third empty line)
;third comment
item1=parameter1;parameter2

Because what i need is a parser which parses all empty lines and comments until the keycontent succeeds but this parser cannot discard the chars of the keycontent parser.

**Comment by nblumhardt** [comment]
In this situation, writing your own version of Sprache's `Token()` method that consumes comments as well as whitespace is the way to go. Hope this provides some clues, if not please feel free to post for more info.

**Comment by JohanLarsson** [comment]
Perhaps better to ask on StackOverflow. More useful for others if it is answered there.
