### ISSUE TITLE
Counting Spaces or Tabs?

### ISSUE THREAD

**Issue by fruitbatinshades** [sprache/Sprache#63]
I'm trying to count the indentation of a file but WhiteSpace.Many() return 0 matches as does .Char('\t') for tabs

from depth in Parse.WhiteSpace.Many()

Any ideas how to count whitespace?

**Comment by nblumhardt** [comment]
Hi - it looks like what you have there should work; are you able to post more of the parser and a sample of the input to give some more clues?

Cheers,
Nick
