### ISSUE TITLE
PCL version incompatible with Xamarin

### ISSUE THREAD

**Issue by kzu** [sprache/Sprache#66]
Xamarin.Forms PCLs currently use profile 111, and we'll switch them to 259 soon.

None of the published nuget versions are compatible with either of those profiles.

**Comment by nblumhardt** [comment]
Hey Daniel! With the _project.json_ tooling in VS2015 usable for easy multi-targeting it'd be a great time for us to switch this project over and broaden platform support. Not sure I'll have time to look at it in the very near future, but open to PRs if anyone is keen to pick it up (now or when RC2/`dotnet` drops). Marking "up for grabs" :-)

**Comment by kzu** [comment]
yeah, sounds good. Will see if I can make the time. Would be a fun way to
learn how to do it ;)

**Comment by lvermeulen** [comment]
Porting to .netstandard would actually take care of this, see [.NET Standard Library Support for Xamarin](https://blog.xamarin.com/net-standard-library-support-for-xamarin/)

**Comment by nblumhardt** [comment]
`develop` (2.1) now uses project.json and targets `netstandard1.6`. We have #74 to cover adding the other supported platforms, so now would be a great time to cover this one.

**Comment by nblumhardt** [comment]
This should be dealt with by #75
