### ISSUE TITLE
using sprache regex question

### ISSUE THREAD

**Issue by braifman** [sprache/Sprache#69]
I would like to parse a string like this: 
"country AND city AND town"

and return just the matches "country" "city" and "town"  

This is the regex pattern i came up with: string pattern = "[^AND]+([^AND]+)*"

Can you show me how to do this using a sprache.

I tried:

var andParser = 
      Parse.Regex(pattern).Many()

This only gives me the word "country" and not "city" and "town" 
Two questions: 
1) Is there an easier way in sprache to get these three words split by AND 
2) In this example is it my regex pattern or my sprache rule that doesn't work because I have tried this pattern with normal regex library and it worked fine

**Comment by nblumhardt** [comment]
Hi @braifman - the trick with Sprache is to build small parsers and then put them together to make larger ones. The first thing to do here is to build one that parses `AND`:

```csharp
var and = Parse.String("AND");
```

Another to parse the words being connected:

```csharp
var name = Parse.Letter.Many().Text();
```

Finally, connecting them up:

```csharp
var parser = name.Token().DelimitedBy(and);
var names = parser.Parse("country AND city AND town");
```

Cheers!
