### ISSUE TITLE
selecting multiple parts of a from clause

### ISSUE THREAD

**Issue by braifman** [sprache/Sprache#70]
Is there a easy way to select two parts of a from clause?
For example: 

var parsed =
                 from indicator in Parse.Regex("^")
                 from oper in Parse.AnyChar.Except(Parse.String("AND")).Many().Text()
                 from next in Parse.String("AND")
                 from rest in Parse.AnyChar.Many().Text().End()
                 select  oper, rest;

I would like to select both the oper and the rest fields of the from clause and maybe access the elements as if they were placed into an array

**Comment by mpartipilo** [comment]
You can select them all into anything: a tuple, a list, an array, etc. Just do select new List<string>() {oper,rest};

Michelangelo P.
