### ISSUE TITLE
Add all supported platforms to the `develop` version

### ISSUE THREAD

**Issue by nblumhardt** [sprache/Sprache#74]
The 2.1.x .NET Core-compatible build in the develop branch only targets .NET 4.5 and .NET Core 1.0. It should be possible to add all of the other supported targets in project.json to bring it up to match 2.0.x.

**Comment by droyad** [comment]
Current release version targets PCL with : 
net4 (.NET 4.0)
netcore45 (Windows Store App, == win8)
win8 (same as above)
wp8 (phone 8)
sl5 (Sliverlight 5)

These are covered by NetStandard (https://docs.nuget.org/create/targetframeworks)
MonoAndroid
Xamarin.iOS10
MonoTouch

**Comment by droyad** [comment]
I tried Win Store 8 and Phone 8 against the current nuget (NETStandard 1.0) and they work OOTB. SL and .NET 4 are not supported by and NETStandard version, so adding them explicitly is needed.
