### ISSUE TITLE
Schedule of .Net core support

### ISSUE THREAD

**Issue by yantang-msft** [sprache/Sprache#79]
Hey Folks,

I see you recently have some changes to support .Net core. Is there any schedule when it will be fully supported? 

Thanks!

**Comment by nblumhardt** [comment]
Hi Yanming,

2.1.0 has now been published to NuGet, .NET Core should be supported by that build. (It may take a few more minutes for the package to be indexed.)

Please let us know if you hit any issues with it, feedback appreciated.

Regards,
Nick

**Comment by yantang-msft** [comment]
Good to know. Thanks Nick!
