### ISSUE TITLE
Parsing at least one

### ISSUE THREAD

**Issue by r1sc** [sprache/Sprache#82]
I'm writing a parser for an assembly language that has label-constructs that may appear in-line with statements like this:
```
:label    statement
```
they may also appear on empty lines like this:
```
:label
```
and they may not appear at all like this:
```
statement
```

My question is how I write a parser that supports at least one of label or statement?
I first thought about writing something like:
```
private static Parser<Statement> LineParser =
            from label in LabelParser.Optional()
            from statement in StatementParser.Optional()
            select Parse.Concat(label, statement);
```
(LabelParser returns a Statement)
But AFAIK Concat doesn't operate on IOptional's.

Does anyone have an idea how to approach this?
Thanks in advance.

**Comment by nblumhardt** [comment]
Hi Erik,

My memory of `IOptional` is a bit fuzzy, but for "brute force":

```csharp
private static Parser<Statement[]> LineParser =
            from label in LabelParser.Optional()
            from statement in StatementParser.Optional()
            let labelValue = label.HasValue ? new[] { label.Value } : new Statement[0],
            let stmtValue = statement.HasValue ? new[] { statement.Value } : new Statement[0],
            let result = labelValue.Concat(stmtValue).ToArray()
            where result.Any()
            select result;
```

Overall (and in case that doesn't compile ;-)) you might be better off changing the way the statements are collected together, using precedence to detect the label/statement combination (pseudo-code):

```csharp
var item =
    Label.Then(l => Parse.Statement.Select(s => new Statement(l, s.Body))
        .Or(Parse.Statement)
        .Or(Parse.Label);

var items = item.Many();
```

If the subject of `Many()` tries the most complete option first, this will be the result, otherwise it falls back to the individual components.

HTH!
Nick

**Comment by r1sc** [comment]
Great! Thanks for the quick response. You're right, restructuring would probably be a better option. I'll check out your suggestions!

Have a nice day!

**Comment by nblumhardt** [comment]
Thanks Erik, good luck with it! :+1:
