### ISSUE TITLE
Question: Conditional Statements

### ISSUE THREAD

**Issue by ftenario** [sprache/Sprache#84]
Hello,
I have just found Sprache and have some questions.
Will it be able to parse conditional statements like this?

IF ($make == 'big') THEN
    $size = '100'
ELSE
    $size = '50'
END

How will it tokenize multiple lines?

many thanks,
Ferdinand

**Comment by mpartipilo** [comment]
If you  don't make newlines a statement terminator then they are simply ignored.

Conditional statements are possible too. I'm on my phone at the moment but I can dig up an example later if you don't figure it out by yourself.

**Comment by ftenario** [comment]
Thanks
