### ISSUE TITLE
Question: Purpose of Equal tests

### ISSUE THREAD

**Issue by 3dGrabber** [sprache/Sprache#85]
Hi,
What is the purpose of the Equal tests 
[here](https://github.com/sprache/Sprache/blob/develop/src/Sprache/Parse.cs#L260) and [here](https://github.com/sprache/Sprache/blob/develop/src/Sprache/Parse.Sequence.cs#L100)?

**Comment by nblumhardt** [comment]
Hi - I think they're both detecting zero-length matches. If the parser that is the subject of `Many()` doesn't consume any input, it will loop forever. Not sure what kind of grammar this appears in though, sorry. HTH!

**Comment by 3dGrabber** [comment]
Ok, I got it.
Thanks.
