### ISSUE TITLE
intellisense?

### ISSUE THREAD

**Issue by jmagaram** [sprache/Sprache#86]
I tried out this library this morning and love how simple it is to use. Also like the position aware feature which is critical since I want to highlight/color text as the user types it in and certain patterns are found. However I am interested in providing some kind of "intellisense" feature. As the user types in some text I'll parse it and pop up a window showing what text could come next. I don't think there is an easy way to rig this up with Sprache. One thought is I could manipulate the text before parsing to include an explicit cursor character, like "123 45th Avenue NE, |", and then see if it matches a pattern called AwaitingCityStart and then if the input text was "123 45th Avenue NE, Sea|" it might match a pattern for AwaitingCityEnd. Anyway this is just a rough idea; don't know if it would work or how ugly it could get. Is Sprache the right tool for what I'm trying to accomplish or is there some other tool that plays nice with Visual Studio and C# that I could use?

**Comment by jmagaram** [comment]
I read more about this. Doing anything approaching what Visual Studio does is incredibly hard because I need to be able to recognize and deal with incomplete/broken patterns. Maybe I need to explicitly define parsers for all the incomplete patterns I care about. I think Roslyn might work for doing something sophisticated, but this is way beyond what I need.

**Comment by nblumhardt** [comment]
It's a pretty challenging problem. Thanks for the follow-up, and good luck with the project!
