### ISSUE TITLE
A Tip: Using C# 7's Expression bodied methods

### ISSUE THREAD

**Issue by oldrev** [sprache/Sprache#92]
Hello! 
Sprach is a nice library for parsing but Ref() is very annoying. 

In C# 7.0  there is a so called Expression bodied methods can removed the requirement of the Ref() method.

For example:
```csharp
public class MyParser {
    static Parser<IEnumerable<string>> ManyIdents => Ident.Many();
    static Parser<string> Ident => LetterOrDigit.AtLeastOnce().Token().Text();
}
```

cheers!

**Comment by nblumhardt** [comment]
Thanks @oldrev - C# 7 doesn't bring anything new here, though - the example just de-sugars to:

```csharp
    static Parser<IEnumerable<string>> ManyIdents() { return Ident.Many(); }
    static Parser<string> Ident => LetterOrDigit.AtLeastOnce().Token().Text();
```

This is fine, but does cause a new parser to be constructed every time the method is accessed, which won't suit all scenarios.

Cheers!
