### ISSUE TITLE
[SOLVED] Can't use Optional

### ISSUE THREAD

**Issue by xDGameStudios** [sprache/Sprache#94]
When is my problem here I get an error in the 

`from closeBracket in Parse.Char('}').Token()`

and it is because of the 

`from attributes in Attributes`

```
static Parser<string> Inheritance =
            from _ in Parse.Char(':')
            from name in Variable
            select name;

static Parser<List<GMLAttribute>> Attributes =
            from first in Declaration.Or(Assignment).Once()
            from others in (
                    from _ in ListDelimiter
                    from p in Declaration.Or(Assignment)
                    select p).Many()
            select first.Concat(others).ToList();

        static Parser<GMLStruct> Struct =
            from _ in Parse.String("struct")
            from name in Variable
            from parent in Inheritance.Optional()
            from openBracket in Parse.Char('{').Token()
            from attributes in Attributes
            from closeBracket in Parse.Char('}').Token()
            select new GMLStruct(namespaceStack.Peek(), 0, name, parent.IsDefined ?
                                 CurrentNamespace.GetStruct(parent.Get()) : null).AppendAttributes(attributes);
```

Removing it resolves the error! what am I doing wrong?!
It's because of the Attributes ... what am I doing wrong

**Comment by nblumhardt** [comment]
Hi @xDGameStudios - would you be able to post details of the error you receive? Thanks!

**Comment by xDGameStudios** [comment]
/Users/FranciscoDias/Projects/GMStructGenerator/GMStructGenerator/GMLStructParser/GMLStructGrammar.cs(34,34): Error CS1943: An expression of type 'Parser<char>' is not allowed in a subsequent from clause in a query expression with source type 'Parser<<anonymous type: <anonymous type: <anonymous type: <anonymous type: IEnumerable<char> _, string name> <>h__TransparentIdentifier0, string parent> <>h__TransparentIdentifier1, char openBracket> <>h__TransparentIdentifier2, IEnumerable<GMLAttribute> attributes>>'.  Type inference failed in the call to 'SelectMany'. (CS1943) (GMStructGenerator)
