### ISSUE TITLE
Execute function on-the-fly, is it possible?!

### ISSUE THREAD

**Issue by xDGameStudios** [sprache/Sprache#95]
```
static Parser<GMLNamespace> Struct =
            from newStruct in StructDeclaration
            from openBracket in OpenBrackets
            from attributes in Attributes.XOr(Parse.Return<List<GMLAttribute>>(null))
                                         .Then(attributes => newStruct.AppendAttributes(attributes))
            from closeBracket in CloseBrackets
            select CurrentNamespace;
```

This is my code as you can see I'm trying to execute a function in the "Then" method... well as i would expect it doesn't work! is it possible to execute something like this?
I know this is not a issue.. but I really don't know where can I ask for this kind of help!

Thank you in advance

**Comment by mpartipilo** [comment]
This is possible. As long as the return type is right anything that you put in there is executed during parsing. Evaluating the result of the parsing is a whole different thing though.

**Comment by mpartipilo** [comment]
Check out this file where CallFunction is just a method returning and expression:  https://github.com/sprache/Sprache/blob/develop/samples/LinqyCalculator/ExpressionParser.cs

**Comment by smaillet** [comment]
A little late to the party here but I've used the following on a few occasions to get the Semantic actions I think you are after:
```C#
public static Parser<T> OnMatch<T>( this Parser<T> parser, Action<IResult<T>> action )
{
    if( parser == null )
    {
        throw new ArgumentNullException( nameof( parser ) );
    }

    if( action == null )
    {
        throw new ArgumentNullException( nameof( action ) );
    }

    return i =>
    {
        var result = parser( i );
        if( result.WasSuccessful )
        {
            action( result );
        }
        return result;
    };
}
```

You could then use that in your case like this:
```C#
static Parser<GMLNamespace> Struct =
            from newStruct in StructDeclaration
            from openBracket in OpenBrackets
            from attributes in Attributes.XOr(Parse.Return<List<GMLAttribute>>(null))
                                         .OnMatch(attributes => newStruct.AppendAttributes(attributes))
            from closeBracket in CloseBrackets
            select CurrentNamespace;
```
