### ISSUE TITLE
[QUESTION] Best way to Parse a "structure/namespace" like input

### ISSUE THREAD

**Issue by xDGameStudios** [sprache/Sprache#96]
I need to parse something like this:

```
namespace [VarName] {
   namespace [VarName]   {
      struct [VarName] (: [ParentPath]) {
         a = 2, b = 5
      }
   } 
}
```

namespaces can be nested, and inside the struct I have a bunch of variables defined.

**Comment by nblumhardt** [comment]
Hi! Unfortunately whipping up a parser usually still takes a while, so I can't jump in and provide a solution here.

With all of these tasks, generally starting from the smallest units - tokens like the keywords `namespace` and `struct`, and the `VarName` parser - is the way to go.

At the same time, you'll need to build an object model of some type to represent the results - perhaps C# classes called `Namespace`, `Struct`, and `Field` would be a good starting point.

If you haven't read it yet, starting with https://nblumhardt.com/2010/01/building-an-external-dsl-in-c/ should also help.

All the best,
Nick

**Comment by xDGameStudios** [comment]
I've already read the link you recommended... my problem was a specific one.. I can already parse the file ;) my problem is that if I use recursion.

a file contains a namespace the namespace can contain both structs and namespaces.
When I enter a namespace I parse it's

from name in VarName
from containts in Types.Contained(OpenBraces, CloseBraces)
select new Namespace(name).add(contains);

I only create the name space after parsing the contains that can also be namespaces...
so if a struct has a parent the path doesn't exist until I finish the parsing. So how should I link the structs and their parents? should this be done after?! should I create the namespace before parsing it's contents?! I just needed some help in that matter ;)

**Comment by nblumhardt** [comment]
Hope you were able to figure this one out; please let me know if you still need help with this. Cheers!
