### ISSUE TITLE
[SOLVED] Don't allow reserved words?!

### ISSUE THREAD

**Issue by xDGameStudios** [sprache/Sprache#97]
Is there a easy way to not allow reserved words to be used as identifiers?!
I know I can always use Except and then pass a reserved words Parser with a bunch of Or... but is it the best way to approach this problem?!

Another thing is the parsing of reserved terms itself... for example I want to parse the term 
"command"

if I write "commandotherstuff" I still get a positive match for "command" as Sprache doesn't seam to have read token by token, or am I doing something wrong?!

**Comment by nblumhardt** [comment]
Hi @xDGameStudios,

Here's one written-in-browser attempt at the requirements you mention:

```csharp
var reservedWords = new[] { "hello", "world" };

var identifier = Parse.LetterOrDigit
    .Many()
    .Token()
    .Where(t => !reservedWords.Contains(t));

Parser<string> Keyword(string text)
{
    return Parse.String(text)
        .IgnoreThen(Parse.WhiteSpace().Or(Parse.End()))
        .Return(text);
}

var commandIdentifier = from cmd in Keyword("command")
    from ident in identifier
    select $"command - {ident}";
```

Should yield some clues for you, anyway!

Depending on what you're building - it can be tricky to get good error messages from these kinds of parsers (`"unexpected keyword blah, expected identifier"`) - [Superpower](https://github.com/datalust/superpower) was built for this, but the level of documentation currently makes it a bit harder to get started with.

HTH!

**Comment by xDGameStudios** [comment]
Thank you so much for the help ;)

**Comment by nblumhardt** [comment]
You're welcome 👍
