### ISSUE TITLE
Parse.Decimal failing because of unexpected '.' 

### ISSUE THREAD

**Issue by bviala** [sprache/Sprache#98]
Hi,

I'm trying to build a parser with sprache and I'm experiencing trouble with the Parser.Decimal.
It seems that it can't parse any decimal because of the dot character '.'

I've tried to run this very simple test found in Sprache/test/Sprache.Tests/DecimalTests.cs 

`private static readonly Parser<string> DecimalParser = Parse.Decimal.End();`
`Assert.AreEqual("12.23", DecimalParser.Parse("12.23"));`

And it fails and throws 

> Sprache.ParseException : 'Parsing failure: unexpected '.'; expected end of input (Line 1, Column 3); recently consumed: 12'

The weird thing is that if I replace the dot by a comma, then it works just fine:
`Assert.AreEqual("12,23", DecimalParser.Parse("12,23"));` 
does not cause a parsing failure.

My guess is that it might be because I live in a country where we usually use the comma in the decimal notation, and there is some kind of local parameter messing with Sprache.
I have no idea how to fix this though.

Thanks for your help :)

**Comment by mpartipilo** [comment]
You could set the current global culture to one with the expected format from the input. It’s a workaround but it will get the job done.

Michelangelo P.

**Comment by bviala** [comment]
Thank you very much sir !
