### ISSUE TITLE
Update solution to new CSPROJ .NET tooling

### ISSUE THREAD

**Issue by smaillet** [sprache/Sprache#99]
I have multiple version of VS from 2010-2017.x preview and none are able to load any of these "xproj" files. Is there a csproj based solution for this stuff I'm missing somewhere? Just trying to work through the samples on plain desktop .NET Framework ( no .NET core or net standard )

**Comment by nblumhardt** [comment]
Hi @smaillet - thanks for the nudge. The whole solution needs an upgrade to the recent .NET tooling - if anyone out there is keen to attempt it, a PR would be greatly appreciated.

(To get unblocked, you should be able to copy the sample programs into new projects created using your version of VS - HTH!)

**Comment by nblumhardt** [comment]
Fixed in #100
